In [ ]:
import numpy as np

In [ ]:
## Entering x(n) and h(n)

# x = list( map(int,input('Enter the sequence x(n): ').split()) )   ## x = [1, 3, 2, -3, 0, 2, -1, 0, -2, 3, -2, 1]  
# h = list( map(int,input('Enter the sequence h(n): ').split()) )   ## h = [1, 0, 1]

x = [1, 3, 2, -3, 0, 2, -1, 0, -2, 3, -2, 1]  
h = [1, 0, 1]

N=4
M=len(h)

L = N-M+1

In [ ]:
def split_Sequence(x, seqLen, L):
  
  iterations = int(len(x)/L)
  zerosToPadd = M-1

  temp = []
  start = 0
  end = L

  for i in range(iterations):
    sequence = x[start : end]

    arr = sequence
    for j in range (zerosToPadd):
      arr.append(0)

    temp.append(arr)

    start += L
    end += L

  targetArray = np.array(temp)
  targetArray = targetArray.reshape((iterations, seqLen))

  return targetArray

In [ ]:
x = split_Sequence(x, N, L)
x

array([[ 1,  3,  0,  0],
       [ 2, -3,  0,  0],
       [ 0,  2,  0,  0],
       [-1,  0,  0,  0],
       [-2,  3,  0,  0],
       [-2,  1,  0,  0]])

In [ ]:
## Function to handle size of h

def handleSize(h):
  if (len(h) != N):

    for i in range (L-1):
      h.append(0)

  return h

In [ ]:
h = handleSize(h) 
print('h:', h)

h: [1, 0, 1, 0]


In [ ]:
h = np.array(h)
h = h.reshape((1, len(h)))
h.shape

(1, 4)

In [ ]:
## Function to creating circular convolution matrix for h

def handelMatrix(x):
  temp = []
  for i in range (x.size):
    temp.append(np.roll(x, i))

  arr = np.array(temp)
  arr = arr.reshape((x.size, x.size)).T

  return arr

In [ ]:
h = handelMatrix(h)
h

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [ ]:
## Performing Circular Convolution

def circularConvolution(x, h):

  output = []
  rows, cols = x.shape

  for i in range (rows):
    val = h@x[i].T
    val = val.reshape((1, val.size))

    output.append(val)

  y = np.array(output)
  y = y.reshape(rows, cols)

  return y

In [ ]:
y = circularConvolution(x, h)
y

array([[ 1,  3,  1,  3],
       [ 2, -3,  2, -3],
       [ 0,  2,  0,  2],
       [-1,  0, -1,  0],
       [-2,  3, -2,  3],
       [-2,  1, -2,  1]])

In [ ]:
y1 = np.array(y[:, 0:(M-1)])
y1 = y1.flatten()
y1

array([ 1,  3,  2, -3,  0,  2, -1,  0, -2,  3, -2,  1])

In [ ]:
temp = np.array(y1[0:(M-1)])
temp = temp.flatten()
temp

array([1, 3])

In [ ]:
y2 = np.concatenate((temp, y1))
y2

array([ 1,  3,  1,  3,  2, -3,  0,  2, -1,  0, -2,  3, -2,  1])

In [ ]:
result = y1.copy()

result[0:(M-1)] = 0
# result[-(M-1):] = 0
for i in range (M-1):
  result = np.append(result, 0)
  
result = result.flatten()
result

array([ 0,  0,  2, -3,  0,  2, -1,  0, -2,  3, -2,  1,  0,  0])

In [ ]:
y = np.add(y2, result)
print('y:', y)

y: [ 1  3  3  0  2 -1 -1  2 -3  3 -4  4 -2  1]
