In [ ]:
import numpy as np

In [ ]:
X = list( map(complex, input('Enter the sequence x(n): ').split() )  )  # X = 10.+0.j -2.+2.j -2.+0.j -2.-2.j

Enter the sequence x(n): 10.+0.j -2.+2.j -2.+0.j -2.-2.j


In [ ]:
X = np.array(X)
X = X.reshape((1,4))
X

array([[10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j]])

In [ ]:
w = np.array([1,1,1,1,  1,1j,-1,-1j,  1,-1,1,-1,  1,-1j,-1,1j])
w = w.reshape((4,4))
w

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j, -0.-1.j, -1.+0.j,  0.+1.j]])

In [ ]:
x = 0.25*(X@w)
x

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]])

In [ ]:
for index, value in enumerate(x[0]) :
  print('x(', index, ') = ', value )

x( 0 ) =  (1+0j)
x( 1 ) =  (2+0j)
x( 2 ) =  (3+0j)
x( 3 ) =  (4+0j)
