In [ ]:
import numpy as np

**Input sequence x(n)**

In [ ]:
x = list( map(int, input('Enter the sequence x(n): ').split() )  )  # x=[1,2,3,4]

Enter the sequence x(n): 1 2 3 4


In [ ]:
x = np.array(x)
x = x.reshape((1,4))
x

array([[1, 2, 3, 4]])

In [ ]:
w = np.array([1,1,1,1,  1,-1j,-1,1j,  1,-1,1,-1,  1,1j,-1,-1j])
w = w.reshape((4,4))
w

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j, -0.-1.j, -1.+0.j,  0.+1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j]])

In [ ]:
X = x@w
X

array([[10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j]])

In [ ]:
for index, value in enumerate(X[0]) :
  print('X(', index, ') = ', value )

X( 0 ) =  (10+0j)
X( 1 ) =  (-2+2j)
X( 2 ) =  (-2+0j)
X( 3 ) =  (-2-2j)
